### ISSUE TITLE
Vorschlag: mhier-Scan-Hilfe beim Einstellen der korrekten Höhe der Z-Schraube wäre gut.

### ISSUE THREAD

**Issue by Nibbels** [mhier/Repetier-Firmware#12]
Es scheint, als wären viele Drucker extrem verstellt, was die Z-Schraube angeht. Die meisten Nutzer wissen das nicht und sind sich über die Auswirkungen nicht im Klaren.
- Scan Aborted
- Z-Kompensations-Grenzen (g_minComp. ... , g_maxComp...)
- Düsenschleifen
...

Man könnte einen Selbsttest machen, der durch den mhier-Scan und die Abfrage der aktuellen Hotend-Temperatur und Bett-Temperatur dem Nutzer mitteilt, ob seine Z-Schraube ideal eingestellt ist oder gravierend verstellt ist.

Am Ende könnte man am Display anzeigen, ob das OK ist oder nicht.

Vorgehen: 
- Temperatur abfragen und beim Hotend ca. +1um pro °C annehmen.
- Temperatur abfragen und beim Heizbett ca. -1.5um pro °C Grad annehmen
- (Durchgewärmt vs. Kalt sind nur ca. max. 150um unterschied, das allein könnte man tolerieren)
- Hinweis auf saubere Düse geben, Play-Knoipf verlangen.
- mhier-Scan durchführen und Ergebnis verrechnen.
- Solleinstellung: Heißes Hotend bei +0.2 .. +0.3mm, d.h. heißes durchgewärmtes Hotend max. bei ~+0.05 .. +0.15
- Anhand der Steigung der Z-Schraube ausgeben, wieviele Umdrehungen eine Korrektur nach oben oder unten erfordert.

**Comment by Nibbels** [comment]
Völlig klar ist mir dabei auch, dass die Z-Schraube nicht zwingend das Problem sein muss.
Generell sollte man in der Firmware eine Variable haben, die aussagt, wie weit der aktuell verbaute Schalter überfahren werden darf.
Z_OVERRIDE_MAX

Diese Einstellung, bzw das physikalisch vorhandene Offset, sollte eine sinnvolle Auswirkung auf HEAT_BED_Z_COMPENSATION_MAX_MM HEAT_BED_Z_COMPENSATION_MIN_MM Z_OVERRIDE_MAX und andere Begrenzer haben, die fest codiert sind.
Z.B. Suchlimits beim mhier-Scan oder HBS.

Diese Einstellung sollte ebenfalls auf die generelle Z-Höheninterpretation Einfluss nehmen.

**Comment by mhier** [comment]
Solange die Z-Kompensation nicht Bit-Überläufe bekommt, ist es mit dem Z-Scan vollkommen egal, wo die Schraube steht. Selbst positive Kompensations-Offsets funktionieren meines Wissens problemlos. Beim Standard RF1000-Endschalter würde der Z-Schalter kaputtgehen bevor Bit-Überläufe passieren, demnach sollte das alles kein Problem sein...

**Comment by Nibbels** [comment]
Ich hatte mal gehört, dass die Z-Matrix eigentlich immer negativ sein sollte. Und daran hab ich mich anschließend gehalten, weil ich nichts riskieren wollte.

Der Z-Scan bricht z.B. aktuell ab, wenn er was positives produzieren würde.
Heute müsste man evtl. mal überdenken, ob ich in diesem Punkt nicht zu restriktiv war.

**Comment by mhier** [comment]
Vielleicht täusche ich mich in dem Punkt, müsste man prüfen. Letzlich genügt aber ja dann die Fehlermeldung beim Z-Scan. Sofern der korrekt durchlaufen wurde, spielt die Einstellung der Z-Schraube keine Rolle.

**Comment by Nibbels** [comment]
Zumindest ein Z-Homing von über einer positiven Matrix-Position kracht theoretisch in die Platte.

**Comment by mhier** [comment]
Das stimmt. Ich sehe ja nach wie vor keinen Sinn darin, einzelne Achsen zu homen...

**Comment by Wessix** [comment]
doch mache ich ab und zu. Ob das andere jetzt als sinnvoll erachten sei mal dahingestellt. aber manchmal erledige ich z.b. Reinigungsarbeiten und rekonditionierungsarbeiten bei heißem Druckbett. Dazu fahre ich auf halbe höhe und bewege nur in Y Richtung. Wenn ich dann jedesmal ganz hoch fahren müsste wäre das extrem nervig ...

**Comment by Nibbels** [comment]
Diese neue Funktion ist nun am Ende dem Z-Offset-Scan eingebunden:
https://github.com/Nibbels/Repetier-Firmware/blob/community_development/Repetier/RF.cpp#L2170

> 0:31:17.505: ZOS(): STEP 9 : GOTO z=0
0:31:19.663: X:80.00 Y:90.00 Z:-0.87 E:0.00
0:31:19.759: ZOS(): finished (2)

> 0:31:19.759: Z-Schrauben-Helper:
0:31:19.801: - Alle Werte in Mikrometern / Einheit [um] -
0:31:19.802: Matrix-Minimum: -796.48
0:31:19.802: Weitere Extruderausdehnung maximal: 253.05
0:31:19.802: Weitere Heizbettausdehnung maximal: 146.77
0:31:19.802: Minimalabstand bei Maximaltemperaturen: -396.66
0:31:19.803: Wenn das Druckergehaeuse gerade durchgewaermt waere: -396.66
0:31:19.803: Wenn das Druckergehaeuse gerade kalt waere: -546.66
0:31:19.803: #############
0:31:19.803: Sollkorrektur: 197 [um] = 0.197 [mm]
0:31:19.803: Sollumdrehungen: 0.4 (weiter reindrehen)
0:31:19.804: (RF2000: Minimal eine halbe Schraubendrehung einstellbar.)
0:31:19.804: #############

Nach der Korrektur:
(Erneuter Z-Offset-Scan)

> 0:37:08.258: Z-Schrauben-Helper:
0:37:08.258: - Alle Werte in Mikrometern / Einheit [um] -
0:37:08.258: Matrix-Minimum: -544.92
0:37:08.258: Weitere Extruderausdehnung maximal: 252.85
0:37:08.259: Weitere Heizbettausdehnung maximal: 146.62
0:37:08.259: Minimalabstand bei Maximaltemperaturen: -145.45
0:37:08.259: Wenn das Druckergehaeuse gerade durchgewaermt waere: -145.45
0:37:08.259: Wenn das Druckergehaeuse gerade kalt waere: -295.45
0:37:08.260: #############
0:37:08.260: Sollkorrektur: -55 [um] = -0.055 [mm]
0:37:08.260: Sollumdrehungen: -0.1 (RF2000: Die Z-Schraube ist ok!)
0:37:08.274: (RF2000: Minimal eine halbe Schraubendrehung einstellbar.)
0:37:08.274: #############

💃  🗡 :D
