### ISSUE TITLE
Compiling Error with FEATURE_EXTENDED_BUTTONS 0

### ISSUE THREAD

**Issue by ghost** [mhier/Repetier-Firmware#152]
If Feature Extended Buttons is deactivated, there will be errors during compiling (EEPROM.h)
#define FEATURE_EXTENDED_BUTTONS            0 

`Arduino: 1.8.4 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

sketch\Eeprom.cpp: In static member function 'static void EEPROM::restoreEEPROMSettingsFromConfiguration()':

Eeprom.cpp:302: error: 'g_nManualSteps' was not declared in this scope

     g_nManualSteps[X_AXIS] = uint32_t(Printer::axisStepsPerMM[X_AXIS] * DEFAULT_MANUAL_MM_X); 

     ^

Eeprom.cpp:302: error: 'DEFAULT_MANUAL_MM_X' was not declared in this scope

     g_nManualSteps[X_AXIS] = uint32_t(Printer::axisStepsPerMM[X_AXIS] * DEFAULT_MANUAL_MM_X); 

                                                                         ^

Eeprom.cpp:303: error: 'DEFAULT_MANUAL_MM_Y' was not declared in this scope

     g_nManualSteps[Y_AXIS] = uint32_t(Printer::axisStepsPerMM[Y_AXIS] * DEFAULT_MANUAL_MM_Y);

                                                                         ^

Eeprom.cpp:304: error: 'DEFAULT_MANUAL_MM_Z' was not declared in this scope

     g_nManualSteps[Z_AXIS] = uint32_t(Printer::axisStepsPerMM[Z_AXIS] * DEFAULT_MANUAL_MM_Z);

                                                                         ^

Eeprom.cpp:305: error: 'DEFAULT_MANUAL_MM_E' was not declared in this scope

     g_nManualSteps[E_AXIS] = uint32_t(Extruder::current->stepsPerMM * DEFAULT_MANUAL_MM_E);

                                                                       ^

sketch\Eeprom.cpp: In static member function 'static void EEPROM::storeDataIntoEEPROM(uint8_t)':

Eeprom.cpp:550: error: 'g_nManualSteps' was not declared in this scope

     HAL::eprSetInt32( EPR_RF_MOD_Z_STEP_SIZE, g_nManualSteps[Z_AXIS] );

                                               ^

sketch\Eeprom.cpp: In static member function 'static void EEPROM::readDataFromEEPROM()':

Eeprom.cpp:870: error: 'g_nManualSteps' was not declared in this scope

     g_nManualSteps[X_AXIS] = uint32_t(Printer::axisStepsPerMM[X_AXIS] * DEFAULT_MANUAL_MM_X); 

     ^

Eeprom.cpp:870: error: 'DEFAULT_MANUAL_MM_X' was not declared in this scope

     g_nManualSteps[X_AXIS] = uint32_t(Printer::axisStepsPerMM[X_AXIS] * DEFAULT_MANUAL_MM_X); 

                                                                         ^

Eeprom.cpp:871: error: 'DEFAULT_MANUAL_MM_Y' was not declared in this scope

     g_nManualSteps[Y_AXIS] = uint32_t(Printer::axisStepsPerMM[Y_AXIS] * DEFAULT_MANUAL_MM_Y);

                                                                         ^

Eeprom.cpp:872: error: 'NUM_ACCEPTABLE_STEP_SIZE_TABLE' was not declared in this scope

     const unsigned long stepsize_table[NUM_ACCEPTABLE_STEP_SIZE_TABLE] PROGMEM = ACCEPTABLE_STEP_SIZE_TABLE;

                                        ^

Eeprom.cpp:872: error: 'ACCEPTABLE_STEP_SIZE_TABLE' was not declared in this scope

     const unsigned long stepsize_table[NUM_ACCEPTABLE_STEP_SIZE_TABLE] PROGMEM = ACCEPTABLE_STEP_SIZE_TABLE;

                                                                                  ^

In file included from sketch\HAL.h:56:0,

                 from sketch\Repetier.h:44,

                 from sketch\Eeprom.cpp:19:

Eeprom.cpp:874: error: 'stepsize_table' was not declared in this scope

     g_nManualSteps[Z_AXIS] = uint32_t(constrain( (unsigned long)HAL::eprGetInt32( EPR_RF_MOD_Z_STEP_SIZE )*Printer::axisStepsPerMM[Z_AXIS]/2560 , 1 , stepsize_table[NUM_ACCEPTABLE_STEP_SIZE_TABLE-1]*Printer::axisStepsPerMM[Z_AXIS]/2560 ) ); //limit stepsize to value in config.

                                                                                                                                                       ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:95:60: note: in definition of macro 'constrain'

 #define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))

                                                            ^

Eeprom.cpp:875: error: 'DEFAULT_MANUAL_MM_E' was not declared in this scope

     g_nManualSteps[E_AXIS] = uint32_t(Extruder::current->stepsPerMM * DEFAULT_MANUAL_MM_E); //current extruder stepsPerMM weil hier noch kein update fÃ¼r Printer::axisStepsPerMM[E_AXIS] gemacht wurde!

                                                                       ^

exit status 1
'g_nManualSteps' was not declared in this scope

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.
`

**Comment by Nibbels** [comment]
Hello,

why would you want to deactivate this feature?

This firmware is for RF1000/RF2000/RF2000v2 printers only. Those extended buttons are hardware buttons which are build into all of these printer types.

(There are many switches you cannot switch off. I removed some of them and fully merged this code by removing all the "#if FEATURE"-Places)
But yes, those "Feature_xxxx" defines which are completely melted into the firmware should be removed from the configuration.

Greetings
