### ISSUE TITLE
Vorschlag: Geschwindigkeitsdrosselung oder Auto-Pause bei extrem hohen Digits (Limit einstellbar)

### ISSUE THREAD

**Issue by Nibbels** [mhier/Repetier-Firmware#18]
Ähnlich SenseOffset, nur sollte das die Geschwindigkeit runterregeln und notfalls in ner Pause landen.
Wenn das Hotend ausfällt oder die Düse zukokelt wäre das ein ganz praktisches Feature.
(Verhindert Ritzeldurchdrehen oder Extruderklackern)

Die Temperatur müsste im Fall einer Pause beim Extruder runter, beim Hotend nicht.

**Comment by Wessix** [comment]
und einen Versuch in eine "frei" position zu fahren eine und dan versuchen nach etwas zeit ganz vorsichtig etwas zu extrudieren und zu schauen ob die digit werte dann fallen. quasi freispülen im leeren raum.

**Comment by Nibbels** [comment]
**Die Auto-Pause gibts schon.**

Das ist die Emergency-Pause.
Die kann man aufbohren, in dem man zweimal "pausePrint();" statt einmal Pauseprint einfügt. Dann fährt der Druckkopf bei Problemen auch korrekt vom Bauteil weg.

[Das System kann man verbessern indem beim Knopfdruck auf Extrude und Retract der Rückfahr-E-Wert genullt wird. Dann landet man nicht durch manuelles Extrudieren mit den Tasten im Emergency-Block wenn man Fortführen drückt.]

Anschließend kann man M3075 S-xxxxx Pxxxxx nutzen um die Max-Digits einzustellen.
Klappt gut, aber der Bug https://github.com/RF1000community/Repetier-Firmware/issues/34 hängt da mit drin.

RF1000 weiß bescheid und hat ein Bugvideo.
Ich warte gespannt...

**Comment by Nibbels** [comment]
Das hier wäre besonders für PETG gut.
Allerdings funktioniert weniger Geschwindigkeit hier nicht :) In dem Fall braucht man bei hohen Digits meist einen Pull oder etwas Oiling.

Da es Auto-Pause schon gibt, schließe ich diese Idee.

LG
