### ISSUE TITLE
SenseOffset Scharfstellung als kleines Symbol im Modmenü zeigen.

### ISSUE THREAD

**Issue by Nibbels** [mhier/Repetier-Firmware#31]
Wenn jemand im Slicer eine Höhenveränderung (logisches Z-Offset) einstellt, die allerdings der Drucker nicht kennt, ist manchmal die Schwelle für die SenseOffset-Höhenlimitierung schon überschritten.

Darum wärs für die Schnellhilfe und Kontrolle gut, wenn wir im Display ein kleines Zeichen haben, solange der Drucker denkt, er wäre im ersten Layer.

**Comment by Wessix** [comment]
Absolut dafür

**Comment by mhier** [comment]
Ich bin ja immer noch eher unglücklich über diese recht undurchsichtigen Automatismen, aber durch eine solche Anzeige wird es zumindest etwas durchsichtiger.

**Comment by Nibbels** [comment]
In meiner Testversion ändert sich nun das @ zu nem ^, solange die Regelung aktiv ist.

Beim Test gerade war z.B. bei der Startmade noch "@ 2800" dringestanden und solange er überwacht "^ 2800"
Ist glaub gut!

LG

**Comment by Nibbels** [comment]
https://github.com/RF1000community/Repetier-Firmware/commit/82a653195f6b4774521b3523cb6fb7365ba26e3a

Beim nächsten Stable ist das mit drin. Ich teste nun genauer.

**Comment by mhier** [comment]
Bitte entsprechend auch in der Dokumentation ergänzen!

**Comment by Nibbels** [comment]
Richtig, wollte ich, habs aber vergessen.
Jetzt ist das mit dem Zeichen in der changelog und der Readme erwähnt und ich habe zwei neue Screenshots eingearbeitet.

**Comment by Nibbels** [comment]
https://github.com/RF1000community/Repetier-Firmware/commit/1d755c4e43164a99832c639b6a8627169999a0eb

Schaut mal bitte, was fehlen könnte. Dann schließen. :)

**Comment by mhier** [comment]
Sieht gut aus, danke!
