### ISSUE TITLE
Änderung Einleitender Text bezüglich support von mhier

### ISSUE THREAD

**Issue by Wessix** [mhier/Repetier-Firmware#35]
Da mhier ja mitlerweile im Boot ist sollte der Satz das diese Version nicht vom Ersteller des Z-Offset Scans unterstützt wird evtl. mit seinem Einverständnis gestrichen werden

**Comment by mhier** [comment]
Den Satz hab ich wohl übersehen damals. Bitte gerne entfernen ☺️

**Comment by Wessix** [comment]
hab das mal comitted

**Comment by Nibbels** [comment]
hehe top  jetzt weiß ich auch wie Assign geht :D

**Comment by Nibbels** [comment]
Ok.... jetzt ist das in der Stable geändert, aber in der development nicht. kannst du, mhier, das automatisiert in der development einfügen, ohne die dortigen Anderungen zu überschreiben?

**Comment by Nibbels** [comment]
https://github.com/RF1000community/Repetier-Firmware/commit/ccc5c2f323a1f1c02e750a0ad0a204a277d8761f

**Comment by mhier** [comment]
Am besten nächstes Mal in den development branch committen, dann kommt sowas automatisch beim Release mit (oder man kann es cherry-picken). Eigentlich sollte man in den stable branch nie direkt committen.
