### ISSUE TITLE
Bugfix: Emergency Block durch manuelle Steuerung unmöglich machen

### ISSUE THREAD

**Issue by Nibbels** [mhier/Repetier-Firmware#5]
Wenn man mit 1mm, 10mm, 50mm Schritten gehomed in -Z fährt, überfährt man fast mit Sicherheit die Marke Z_OVERRIDE_MAX. Das ist dämlich und sollte verhindert werden. Wirkung: Emergency Block und der Drucker friert (nach Notfall-Plan) ein.

Ebenso:
Wenn man gehomed in -Z fährt, indem man MOVE_MODE_SINGLE_MOVE nutzt, landet man je nach Zufall/Geschwindigkeit in Emergency Block (Because of Z-Min) oder korrekt in "Error Z-Axis Min Reached"

**Comment by Nibbels** [comment]
https://github.com/RF1000community/Repetier-Firmware/pull/17

Wäre damit erledigt.

**Comment by mhier** [comment]
Im Fräsmodus verhindert das jetzt aber, dass ich definiert über das Menü in negative Z-Bereiche fahren kann. Das ist im Fräsmodus was ganz Normales, denn Z=0 ist die Oberfläche des Objektes und Z<0 liegt im Objekt. Ich bohre z.B. immer mein Referenzloch beim PCB-Fräsen über das Menü, dazu möchte ich auf Z=-2mm fahren.

Sollte man vielleicht eine Ausnahme einbauen, falls der Drucker sich gerade im Fräsmodus befindet?

**Comment by Nibbels** [comment]
Ist inzwischen schon als Ausnahme eingebaut, nur aktuell noch ungetestet.

**Comment by Nibbels** [comment]
Kann man das schließen? Test erfolgreich?

**Comment by mhier** [comment]
Also für mich funktioniert es (nur im Fräsmodus getestet). Ich schließe es dann mal.
